version: 2.1
orbs:
  node: circleci/node@4.9.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn build
workflows:
  build:
    jobs:
      - build
